name: $(version)-$(BuildId)

trigger: none

variables:
  - name: version
    value: '0.0.8'
    
resources:
   repositories:
   - repository: templates
     type: git
     name: Templates/Pipelines.NugetPublisher

pool:
  vmImage: ubuntu-latest

extends:
  template: nuget-publisher.yml@templates
  parameters:
    publishProject: '**/ImprovedConsole.csproj'
    runUnitTests: true
    testProject: '**/ImprovedConsole.Tests.csproj'
    version: ${{ variables.version }}
    environment: push-nuget
