name: $(version)-$(BuildId)

trigger: none

variables:
  - name: version
    value: '0.0.1'
  - name: previewVersion
    value: '${{variables.version}}-preview-$(Build.BuildId)'

parameters:
  - name: isPreviewVersion
    displayName: 'Is this a preview version?'
    type: boolean
    default: true
    
resources:
   repositories:
   - repository: templates
     type: git
     name: Templates/Pipelines.NugetPublisher

pool:
  vmImage: ubuntu-latest

extends:
  template: nuget-publisher.yml@templates
  parameters:
    environment: push-nuget
    publishProject: '**/ImprovedConsole.csproj'
    testProject: '**/ImprovedConsole.Tests.csproj'
    ${{ if eq(parameters.isPreviewVersion, 'true') }}:
      version: '${{ variables.previewVersion }}'
    ${{ else }}:
      version: ${{ variables.version }}
